### PR TITLE
TECH-6150 dropped support for rails 4

### PR DESCRIPTION
**Pull request by irismoini**

### CODE REVIEW

**Comment by irismoini** [comment]
Should I also remove the code running tests for rails 4?

**Comment by yinonrousso** [comment]
> Should I also remove the code running tests for rails 4?

Yes, we no longer need to test against rails 4!

**Review by yinonrousso — CHANGES_REQUESTED** [review]
Looking great so far! As mentioned above there is a bit more cleanup work we can add to flush out the remnants of Rails 4 in this gem:

1. Update the `Gemfile` rails dependency to  `~> 5.2` and the activerecord gemspec dependency in to `'>= 5.2', '< 7'`
2. Drop appraisal support for rails 4.
The simplest way I can think of is to remove the `appraise 'rails-4'` block in the Appraisal file then clean up the associated rails 4 gemfile by running `bundle exec appraisal clean && bundle exec appraisal update`
3. Remove the rails 4 gemfile from the github actions workflow matrix

**Comment by ColinDKelley** [comment]
Looks good!

Can you make a major version bump to `version.rb` and `bundle install` that, and add an entry in the CHANGELOG for that?

**Review by yinonrousso — APPROVED** [review]
LGTM! One last NIT that came to mind is to update the [README Support](https://github.com/Invoca/activerecord-mysql-enum#support) section to reflect the newly supported test versions

**Pull request merged**
